// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Agencies.iOS
{
	public partial class BotNavigationController : UINavigationController
	{
		public BotNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
