// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Agencies.iOS
{
	public partial class GroupsTableViewController : UITableViewController
	{
		public GroupsTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
