/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

    public static class SettingsKeys
    {

        #region Visible Settings

        public const string VersionNumber = "VersionNumber";

        public const string BuildNumber = "BuildNumber";

        public const string GitCommitHash = "GitCommitHash";

        public const string UserReferenceKey = "UserReferenceKey";

        #endregion


        #region Hidden Settings

        public const string SelectedTabIndex = "SelectedTabIndex";

        #endregion


        #region Debug
#if DEBUG

        public const string UseLocalServer = "UseLocalServer";

        public const string ResetConversation = "ResetConversation";

#endif
        #endregion
    }
}